# 1. Load the Dataset

In this section, we create and load a sample retail sales dataset.

The dataset contains customer, product, sales, payment, and rating information.

We will use this dataset throughout the EDA Mini Challenge.

In [1]:
# Import Pandas
import pandas as pd

# Create the DataFrame
df = pd.DataFrame({
    "Order_ID": [1001, 1002, 1003, 1004, 1005],
    "Customer_Age": [25, 34, 29, 42, 31],
    "Gender": ["Male", "Female", "Female", "Male", "Female"],
    "City": ["Chennai", "Bangalore", "Chennai", "Hyderabad", "Bangalore"],
    "Category": ["Electronics", "Clothing", "Grocery", "Electronics", "Furniture"],
    "Quantity": [2, 3, 5, 1, 2],
    "Unit_Price": [500, 800, 200, 1500, 1200]
})

# Display first 5 rows
df.head()

,Order_ID,Customer_Age,Gender,City,Category,Quantity,Unit_Price
0,1001,25,Male,Chennai,Electronics,2,500
1,1002,34,Female,Bangalore,Clothing,3,800
2,1003,29,Female,Chennai,Grocery,5,200
3,1004,42,Male,Hyderabad,Electronics,1,1500
4,1005,31,Female,Bangalore,Furniture,2,1200

# Topic 2 – Understand the Dataset

Now you need to find:

Number of rows
Number of columns
First 5 rows
Last 5 rows
Fill-in practice

In [2]:
# Number of rows and columns
df.shape

# First 5 rows
df.head()

# Last 5 rows
df.tail()

,Order_ID,Customer_Age,Gender,City,Category,Quantity,Unit_Price
0,1001,25,Male,Chennai,Electronics,2,500
1,1002,34,Female,Bangalore,Clothing,3,800
2,1003,29,Female,Chennai,Grocery,5,200
3,1004,42,Male,Hyderabad,Electronics,1,1500
4,1005,31,Female,Bangalore,Furniture,2,1200

 ## Topic 3 – Inspect the Structure

Since you said next, here is the answer and we'll continue.

####  Inspect DataFrame structure
df.info()


####  Display column names
df.columns


####  Check data types
df.dtypes
What you should understand
df.info() → overall DataFrame structure
df.columns → column names
df.dtypes → data type of each column

# Topic 4 – Identify Data Types

Now you practice.

Your task

## From the dataset, identify:

- Numerical columns
- Categorical columns
- Date columns

In [ ]:
# Display the data types
df.dtypes

# Select numerical columns
numerical_columns = df.select_dtypes(include="number").columns

# Select categorical columns
categorical_columns = df.select_dtypes(include="object").columns

print("Numerical Columns:", numerical_columns)
print("Categorical Columns:", categorical_columns)

# Topic 5 – Missing Values

Now you need to discover whether the dataset contains missing values.

Your task

Find:

Missing values in each column
Total number of missing values
Whether the dataset contains any missing values at all

In [ ]:
# Missing values in each column
df.isnull().sum()

# Total missing values
total_missing = df.isnull().sum().sum()

print("Total Missing Values:", total_missing)

# Check whether any missing value exists
df.isnull().any().any()

# Topic 6 – Identify Duplicates

Now you practice.

Your task

Find:

- Number of duplicate rows
- Whether any duplicate exists
- Display the duplicate rows

In [ ]:
# Count duplicate rows
duplicate_count = df.duplicated().sum()


print("Duplicate Rows:", duplicate_count)


# Check whether duplicates exist
df.duplicated().any()


# Display duplicate rows
df[df.duplicated()]
Remember
duplicated()          → identify duplicates
duplicated().sum()    → count duplicates
duplicated().any()    → check if duplicates exist
df[df.duplicated()]   → display duplicates

Important: Your current small dataset has no duplicates, so the result will be 0 / False / an empty DataFrame.

# Topic 7 – Numerical Analysis

Now you need to analyze the numerical columns.

Your task

Find:

- Count
- Mean
- Standard deviation
- Minimum
- 25th percentile
- Median (50%)
- 75th percentile
- Maximum
Fill in the blank

In [ ]:
# Statistical summary of numerical columns
df.describe()

# Topic 8 – Categorical Analysis

Now your job is to understand the categories and their frequencies.

You need to find
How many unique values each categorical column has
Which categories exist
How frequently each category occurs

We already identified these categorical columns:

Gender
City
Category

In [ ]:
So:

# Gender frequency
df["Gender"].value_counts()


# City frequency
df["City"].value_counts()


# Category frequency
df["Category"].value_counts()
Remember
unique()        → shows the unique values
nunique()       → counts how many unique values
value_counts()  → counts how many times each value occurs

For example:

df["Gender"].unique()

might give:

['Male', 'Female']

while:

df["Gender"].value_counts()

gives something like:

Male      3
Female    2
unique()        → Show unique values
nunique()       → Count unique values
value_counts()  → Count each value's frequency

# Topic 9 – Outlier Detection

Now we're going to find unusual values in numerical columns.

For this challenge, practice the IQR method.

Your task

For the Customer_Age column, find:

Q1
Q3
IQR
Lower limit
Upper limit
Values outside those limits

In [ ]:
Q1 = df["Customer_Age"].quantile(0.25)
Q3 = df["Customer_Age"].quantile(0.75)

IQR = Q3 - Q1

lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

outliers = df[
    (df["Customer_Age"] < lower_limit) |
    (df["Customer_Age"] > upper_limit)
]

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower Limit:", lower_limit)
print("Upper Limit:", upper_limit)
print("Outliers:")
print(outliers)

# Topic 10 – Distribution Analysis

Now you need to look at the distribution, not just calculate statistics.

Choose one numerical column first: Customer_Age.

Your task

Create a histogram and answer:

Is the distribution roughly symmetric?
Is it left-skewed or right-skewed?
Where are most observations concentrated?
Are there any unusual values?

What are we trying to do?

We have numerical values:

Customer_Age
25, 34, 29, 42, 31, ...

We want to see how these ages are distributed.

The appropriate chart is a histogram.

In Pandas:

kind="hist"
What are bins?

bins controls how many groups the values are divided into.

For example:

bins=5

means roughly 5 age ranges.

For our small practice dataset, we'll use 5.

Correct code
import matplotlib.pyplot as plt


df["Customer_Age"].plot(
    kind="hist",
    bins=5
)


plt.xlabel("Customer Age")
plt.ylabel("Frequency")
plt.title("Customer Age Distribution")
plt.show()

# Topic 11 – Correlation Analysis

Now we want to find relationships between numerical variables.

Our numerical columns include:

Customer_Age
Quantity
Unit_Price

Later, we will also have Total_Sales.

Your task

Find the correlation between all numerical columns.

Fill in the blank
# Calculate correlation between numerical columns
correlation = df.________(numeric_only=True)


print(correlation)

In [ ]:
# Calculate correlation between numerical columns 
correlation = df.corr(numeric_only=True) 
 
print(correlation)

Perfect ✅ df.corr(numeric_only=True) is correct.

In [ ]:
Let's solve each one.

Chart 1 — Category Comparison

We want to know:

How many orders belong to each category?

First, value_counts() counts each category:

df["Category"].value_counts()

Then we want a bar chart, because we're comparing categories.

kind="bar"

So:

import matplotlib.pyplot as plt


df["Category"].value_counts().plot(kind="bar")


plt.xlabel("Category")
plt.ylabel("Number of Orders")
plt.title("Orders by Category")
plt.show()
Remember

Categorical comparison → Bar chart

Chart 2 — Numerical Relationship

We want to see:

Does Quantity have a relationship with Unit_Price?

Both are numerical variables.

The appropriate chart is a scatter plot.

df.plot(
    x="Quantity",
    y="Unit_Price",
    kind="scatter"
)


plt.xlabel("Quantity")
plt.ylabel("Unit Price")
plt.title("Quantity vs Unit Price")
plt.show()
Remember

Numerical + Numerical → Scatter plot

Chart 3 — Outlier Visualization

We want to find unusual values in Unit_Price.

The appropriate chart is a box plot.

df["Unit_Price"].plot(kind="box")


plt.ylabel("Unit Price")
plt.title("Unit Price Outlier Analysis")
plt.show()
Remember this chart-selection rule
Categorical comparison     → Bar chart
Numerical distribution     → Histogram
Numerical + Numerical      → Scatter plot
Outlier detection          → Box plot
Correlation matrix         → Heatmap

You've now covered the main technical EDA steps. ✅

T